### ISSUE TITLE
Custom rules config does not working

### ISSUE THREAD

**Issue by CatsMiaow** [IBM/report-toolkit#102]
https://ibm.github.io/report-toolkit/config/#customizing-the-%22recommended%22-configuration

The setting values below do not working
`.rtkrc.js`
```js
exports.config = ['rtk:recommended', {
  rules: {
    'cpu-usage': true,
    'library-mismatch': false,
    'long-timeout': true,
    'memory-usage': true,
  },
}];
```

```sh 
rtk --rc .rtkrc.js inspect report1.json
```

https://github.com/IBM/report-toolkit/blob/f009e704354dea4a8709a515e46c5930611567c2/packages/core/src/observable.js#L125-L126

Since the passed `config.rules` value is an object, there is no `length` property, so `ruleIdsCount` always returns 0

**Comment by boneskull** [comment]
hmm, okay, I'll look at this. thanks

**Comment by boneskull** [comment]
confirmed. will have a fix out shortly
